# -*- coding: utf-8 -*-
"""Assignment.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ZA0OWw5LIMMnhg5Jsw_6g7FCrRin5EE4

Python Code for Extracting JSON Data
"""

import requests
import pandas as pd

# Raw GitHub JSON link
url =  "https://raw.githubusercontent.com/moraraba/Working-with-Json/refs/heads/main/MOCK_DATA.json"

# Request data
response = requests.get(url)

# Convert JSON response
data = response.json()

# Convert to DataFrame
df = pd.DataFrame(data)

# Display first rows
print(df.head())

# Save as CSV
df.to_csv("synthetic_data.csv", index=False)

print("CSV file saved successfully.")

"""# Working with DummyJSON API Endpoints
Products Endpoint
"""

import requests
import pandas as pd

# Products endpoint
url = "https://dummyjson.com/products"

# Send request
response = requests.get(url)

# Convert to JSON
data = response.json()

# Extract products
products = data['products']

# Convert to DataFrame
products_df = pd.DataFrame(products)

# Display data
print(products_df.head())

# Save CSV
products_df.to_csv("products_data.csv", index=False)

print("Products CSV saved successfully.")

"""Carts Endpoint"""

import requests
import pandas as pd

# Carts endpoint
url = "https://dummyjson.com/carts"

# Send request
response = requests.get(url)

# Convert JSON response
data = response.json()

# Extract carts
carts = data['carts']

# Convert to DataFrame
carts_df = pd.DataFrame(carts)

# Display data
print(carts_df.head())

# Save CSV
carts_df.to_csv("carts_data.csv", index=False)

print("Carts CSV saved successfully.")